UPDATE pages SET meta_description = 'Uzlabota Pretty URL sistēma ar PHP un .htaccess — draudzīgu adrešu otrā versija.' WHERE id = 60205;
UPDATE pages SET meta_description = 'Smieklīgi joki un jautras anekdotes: 100 joki par blondīnēm. Lasot rakstu, garantēts labs garastāvoklis!' WHERE id = 1155;
UPDATE pages SET meta_description = 'Rakstura īpašības — Sveiki. Šī būs maza rakstura īpašību spēlīte. Tad nu es gribu, lai jūs vienkārši pierakstītu savas: Labās īpašības: Sliktās...' WHERE id = 48121;
UPDATE pages SET meta_description = '(1) Skaitam!! — Noteikumi: 1)Ja tiek ielikta bilde ar numuru 1, tad nākamajai ir jābūt ar nummuru 2, nakamajai ar 3.. 2)Ja piemēram tiek ielikts divas...' WHERE id = 39551;
UPDATE pages SET meta_description = 'Piedalies populārajā exs.lv foruma spēlē "Foruma spēle - Raksturo lietotāju". Iesaisties diskusijās un uzspēlē kopā ar citiem biedriem!' WHERE id = 41857;
UPDATE pages SET meta_description = 'Noderīga pamācība: Kā apmulsināt Idiotu!.' WHERE id = 878;
UPDATE pages SET meta_description = 'GOEXANIMO CS:GO 2x2 #7 — UPDATE: Turnīrā Retake Mode paredzētas nelielas izmaiņas! Lai jau atkal censtos uzlabot T un CT side spēlēs balansu visām...' WHERE id = 69337;
UPDATE pages SET meta_description = 'Lapas lietošanas noteikumi — attiecas uz exs.lv mājaslapu un tās apakšprojektiem coding.lv, runescape.exs.lv un lol.exs.lv. Turpmāk tekstā "exs.lv"...' WHERE id = 57753;
UPDATE pages SET meta_description = 'Smieklīgi joki un jautras anekdotes: Joki par Čaku Norisu. Lasot rakstu, garantēts labs garastāvoklis!' WHERE id = 1079;
UPDATE pages SET meta_description = 'Treasure Trails — Par visām neprecizitātēm un/vai kļūdām ziņot autoram vai kādam modam/adminam! Treasure Trails ir RuneScape mini spēle, kas pieejama...' WHERE id = 32746;
UPDATE pages SET meta_description = 'Klases vakara help!! — Nu vobsen iesakat kadu speli 5. klases vakaram!!Steidzami ceru uz atsaucibu katram exietim kas palidzes cepums!!(no spam and...' WHERE id = 33190;
UPDATE pages SET meta_description = 'Recipe for Disaster — Noris uzlabojumi... The Cook Dwarf Wartface & Bentnoze Pirate Pete Lumbridge Sage Evil Dave Skrach Uglogwee Sir Amik Varze...' WHERE id = 18390;
UPDATE pages SET meta_description = 'Counter-Strike 1.6 \\'\\'uzķīlēšana\\'\\' — Sveiki lasītāji! Pēdejā laikā ar vien vairāk un vairāk ir redzami visādi miniblogi vai ieraksti forumā saistībā ar...' WHERE id = 54872;
UPDATE pages SET meta_description = 'Desert Treasure — Saturs Shadow diamond iegūšana Ice diamond iegūšana Blood diamond iegūšana Smoke diamond iegūšana Piramīda Sarežģītība: Ļoti...' WHERE id = 19108;
UPDATE pages SET meta_description = 'Noderīga pamācība: Pamācība kā dabūt NHL09 Dinamo Rīgu!. Ja lādēsiet jaunu rūsteri, bez kura nevar iztikt, lai šo palaistu, jums jārēķinās, ka jūs...' WHERE id = 41008;
UPDATE pages SET meta_description = 'Pārdodu konsoles, dzelžus un citus zvērus — Zemāk esošais info novecojis, par aktuālajām cenām un citām lietām PM vai tepat. Sony Playstation 4 500GB -...' WHERE id = 64344;
UPDATE pages SET meta_description = 'Treniņu programma - 4 day split + shock week programma — Programmas ir dažādas, un katram tās ir jāpiemēro sev, bet man liekas, ka šitā varētu būt laba...' WHERE id = 47577;
UPDATE pages SET meta_description = 'Counter Strike Source serveri — Iesakiet kādu cs:s serveri. Izņemot wos un gamerx.Un nesakiet Gign.lv jo tur tajos serveros nav ppl.' WHERE id = 32733;
UPDATE pages SET meta_description = 'Paspēlēsim spēlīti :D — spēle ir elementāra taču interesanta. es sākšu pirmais sakot kādu vārdu bet nākamajam kas iepostos šajā blogā raksta vārdu...' WHERE id = 48403;
UPDATE pages SET meta_description = 'Monkey Madness — Grūtums: Ļoti sarežģīts Ilgums: Ļoti garš Prasības: Jābūt spējīgam uzvarēt 195. līmeņa dēmonu, stingri ieteicams 43 Prayer, jābūt...' WHERE id = 18318;
UPDATE pages SET meta_description = 'Home Alone — Nosaukums- Home Alone Iznākšanas gads- 1990 Galvenie aktieri- Macaulay Culkin, Daniel Stern, Joe Pesci, John Heard. Žanrs- Komēdija...' WHERE id = 43782;
UPDATE pages SET meta_description = 'Leet Lv | Populārākais latviešu OSRS CC — Sveiki visiem! Vēlos iepazīstināt visus nezinošos ar patreiz populārāko latviešu Old School Runescape...' WHERE id = 69635;
UPDATE pages SET meta_description = 'Latvijas Simulētā Hokeja Līga — Sveiki , exieši. :) Vēlos Jūs iepazīstināt ar ļoti interesantu projektu - Latvijas Simulēto Hokeja Līgu (LSHL). Līga...' WHERE id = 64765;
UPDATE pages SET meta_description = 'How High — Vispariga informacija: Tulkotais nosaukums: Cik augstu (izlēcēji) Oriģinālais nosaukums: How high Režisors: Jesse Dylan Scenārija autors:...' WHERE id = 39888;
UPDATE pages SET meta_description = 'GTA San Andreas — Spēles nosaukums: Grand Theft Auto: San Andreas Žanrs: Action-adventure Izdevējs: Rockstar Games Platforma: Windows, Mac OS X, Xbox,...' WHERE id = 41272;
UPDATE pages SET meta_description = 'Napoleons Bonaparts — Napoleons di Buonaparte (1769 - 1821) Imperators Ievadam Te nu sākas stāsts par, iespējams, atpazīstamāko militāro un politisko...' WHERE id = 61383;
UPDATE pages SET meta_description = '⭐ EliteMU - S6 E3 Original - Pievienojies — ELITEMU - GENERAL INFORMATIONWelcome to EliteMU Online - we are NEW and BIG Private MU Online Server, which...' WHERE id = 69605;
UPDATE pages SET meta_description = 'Uzturs - 80% no rezultāta — Svarīgākais: 75 % -80 % no BB (bodybuilding) rezultātiem ir atkarīgi no uztura un tikai pārējie % no treniņiem un...' WHERE id = 47579;
UPDATE pages SET meta_description = 'Citāti no skolotājiem — Skolotāji. Cilvēki, kas mūs māca. Ne tikai mācību ziņā, bet arī uz visādiem izteicieniem. Šeit es ielikšu dažus klasiskus un...' WHERE id = 40175;
UPDATE pages SET meta_description = 'HyperTown Riga EXPO, Besl.pro Finālspēles un Biļešu izloze! — HyperTown Riga EXPO Šī gada 26-27.maijā Ķīpsalas izstāžu halle norisināsies HyperTown...' WHERE id = 69434;
UPDATE pages SET meta_description = 'Mans veco datoru un tehnikas muzejs — Sveiciens Visiem! Es vācu un restaurēju vecos datorus muzejam, tas ir vienīgas privātais muzejs Baltija. Muzejs...' WHERE id = 54918;
UPDATE pages SET meta_description = '45 jautājumi, uz kuriem vari atbildēt tu ? — 1. Vai var paraudāt zem ūdens? 2. Vai tie kuri sazinās zīmju valodā, galvā redz kā kustās rokas? Kā viņi...' WHERE id = 42114;
UPDATE pages SET meta_description = 'Novērtē dziesmu — Viss pavisam vienkārši! Novērtē iepriekšējā komentētāja dziesmu 10 baļļu skalā un ieliec pats dziesmu, ko novērtēt nāmajam. Atbildot...' WHERE id = 53715;
UPDATE pages SET meta_description = 'Heroes\\' Quest — Saturs Firebird\\'s Feather Master Thieves\\' Armband Cooked Lava eel Grūtums: Grūts Ilgums: Ilgs Prasības: 25 Herblore, 50 Mining, 53...' WHERE id = 18303;
UPDATE pages SET meta_description = 'Kur jūs dosities klases ekskursijā? — Es tā padomāju un gribēju šito topiku uztaisīt par ekskursijām. Kur jūs ar savu klasi brauksiet/iesiet pārgājienā...' WHERE id = 43061;
UPDATE pages SET meta_description = 'Noderīga pamācība: Kā uztaisīt Minecraft serveri. Skatos te daudz čīkst, ka grib savu MineCraft serveri, tāpēc izdomāju uzrakstīt pamācību. 1....' WHERE id = 46742;
UPDATE pages SET meta_description = '100+ Vouches — Piedāvāju MM pakalpojumus, 5% no darījuma summas tiek man par middlemanning, ja darījuma summa pārsniedz 50 eiro. Accountu...' WHERE id = 45030;
UPDATE pages SET meta_description = 'Apbruņojums un pārvietošanās līdzekļi — Lai aizsargātu sevi no briesmoņiem un izdarītu tiem lielāku kaitējumu, jūs varat izveidot apbruņojumu, kurā...' WHERE id = 44066;
UPDATE pages SET meta_description = 'Noderīga pamācība: Kā apdullināt/aizmidzināt sevi ar elpošanu vien + Videos. Šodien mans klasesbiedrs teicās atklājis jaunu veidu kā tikt "high" ar...' WHERE id = 31377;
UPDATE pages SET meta_description = 'Fremennik Trials, The — The Fremennik Trials Saturs Manni the Reveller Swensen the Navigator Sigli the Huntsman Olaf the Bard Peer the Seer Thorvald...' WHERE id = 18293;
UPDATE pages SET meta_description = 'Demon Slayer — Obligātās prasmes: nav! Vajadzīgās mantas: 25 parastie kauli (bones), 1gp Misijas izpilde: Runājiet ar Gypsy Aris, kura atrodas tuvumā...' WHERE id = 18272;
UPDATE pages SET meta_description = 'Exs party 19.-21.08 — Tātad tikai šodien dzima ideja uzrīkot pasākumu exiešiem un jau tagad ir izlemts, kur, kad un kā tas notiks (aptuveni). Tātad...' WHERE id = 47717;
UPDATE pages SET meta_description = 'Avataru spēle 2! — Sveiki, ieraudzīju šo intresanto spēli, kura jūs aizrāva, kā nekā bija pāri 300 postiem.Tātad iedomājos atdzīvināt. : Spēlēs...' WHERE id = 39006;
UPDATE pages SET meta_description = 'Need for Speed Hot Pursuit 2010 — Spēles nosaukums: Need for Speed Hot Pursuit Žanrs: Racing Izdevējs: Electronic Arts Platforma: PC, PlayStation 3,...' WHERE id = 43736;
UPDATE pages SET meta_description = '*100 Pushups — UPDATE. 5. Jūlijs: Palieku stiprāks, foršā vasara. Papildus pievelkos. Čau 50! Pie 60 būs neliela svinēšana :] Update: 16. arpīlis: Var...' WHERE id = 42378;
UPDATE pages SET meta_description = 'South Africa 2010 — Diskutējam par spēlēm, izsakām prognozes. Rezultāti Grupu spēles DĀR- Meksika 1:1 Urugvaja- Francija 0:0 Anglija- ASV 1:1 Alžīrija-...' WHERE id = 41669;
UPDATE pages SET meta_description = 'Интерны — Režisori: Maksims Peženskis, Zaurs Bolotajevs, Milans Kilibarda. Lomās: Ivans Ohlobistins, Iļja Gliņikovs, Kistīna Asmusa, Aleksandrs Iļjins...' WHERE id = 44953;
UPDATE pages SET meta_description = '4games.lv FIFA 18 2x2 LAN @ World of Games — 15. aprīlī Rīgā norisināsies pirmais FIFA 18 (PS4) 2x2 LAN turnīrs ar kopējo balvu fondu €450 apmērā. Un...' WHERE id = 69415;
UPDATE pages SET meta_description = 'Idejas un ieteikumi exs.lv programmēšanas kopienas attīstībai un uzlabošanai.' WHERE id = 50978;
UPDATE pages SET meta_description = 'Smieklīgi joki un jautras anekdotes: Īsās Anekdotes (1). Lasot rakstu, garantēts labs garastāvoklis!' WHERE id = 37931;
UPDATE pages SET meta_description = 'Mana RS Vēsture — Ievads: Beidzot izdomāju, ka pastāstīšu jums par savu RuneScape vēsturi. Daži jau to ir darījuši, citi vēl nav paspējuši, bet, nu, ir...' WHERE id = 42270;
UPDATE pages SET meta_description = 'Uzticamības Kalngals — Yo, nu jau laiciņu es nodarbojos ar savu Servisu (kvestošanā un skilošanā), piedāvāju MM pakalpojumus un veicu dažādus citus...' WHERE id = 44203;
UPDATE pages SET meta_description = 'Regicide — Kvesta garums: Garš Kvesta sarežģītība: Grūts Prasības: Underground Pass, 56 Agility (var būt mazāks Agility, ja lieto dziras utml.), jābūt...' WHERE id = 35386;
UPDATE pages SET meta_description = 'Exs ballīte 2013 — Tava muciņa! 2013. gads mums ir atnesis jau trešo (!) gadskārtējo exiešu salidojumu! Šogad exa ballīte norisināsies 9. un 10....' WHERE id = 57643;
UPDATE pages SET meta_description = 'Kickass 2 — Režisors: Jeff Wadlow Lomās: Aaron Taylor-Johnson, Chloë Grace Moretz, Christopher Mintz-Plasse Īss apraksts: Vidusskolnieks Kickass atkal...' WHERE id = 59269;
UPDATE pages SET meta_description = 'Sapņu komanda 1935 — Galvenie aktieri: Jānis Āmanis, Inga Alsiņa, Vilis Daudziņš, Mārcis Maņjakovs, Mārtiņš Počs, Artūrs Putniņš, Ģirts Ķesteris,...' WHERE id = 52287;
UPDATE pages SET meta_description = 'Fremennik Isles, The — Sarežģītības Pakāpe: Vidēji grūts Ilgums: Vidējs Nepieciešamie Kvesti: The Fremennik Trials Apbalvojums: 1 Quest point, 5000...' WHERE id = 18401;
UPDATE pages SET meta_description = 'Ei tu skaistā meitene — PND Ei tu skaista meitene (akustiski) Kāds kuram muzikālā dzirde un prot spēlēt ģitāru varat pateikt kā jāspēlē? Jau kādu otro...' WHERE id = 43226;
UPDATE pages SET meta_description = 'Urlu baušļi — 1. Tev nebūs paiet garām kādam sīkajam uz ielas un nepaprasīt viņam cigareti, pazvanīt, vai arī pajautāt: kapeiki estj? 2. Tev nebūs...' WHERE id = 40500;
UPDATE pages SET meta_description = '80.-90. gadu krievu mūzika — Sveiki. Krievu valodu es saprotu diezgan labi, bet nu lasīšana un rakstīšana man klibo, jo skolā mācos vācu valodu, a...' WHERE id = 47197;
UPDATE pages SET meta_description = 'Ričarda vouches — Veiksmīgi darījumi bijuši ar šiem lietotājiem: • Mārtiņš • Staipeklis • Anarhists • visel7 • Kiizyy • Rezidents • Part of pkey • Ing...' WHERE id = 53549;
UPDATE pages SET meta_description = 'Knight\\'s Sword, The — Knight\\'s Sword Sākums: Runā Ar Squire Kas atrodas Faladoras Baltajā Bruņinieku Pilī. Prasmes: Tev vajadzīgs 10 Mining, Un Spēks...' WHERE id = 18277;
UPDATE pages SET meta_description = 'BESL Pro - Baltijas eSporta Līga — Baltijas valstis ir mājas aktīvai datorspēļu entuziastu kopienai, kas regulāri savā starpā aizvada dramatiskas spožu...' WHERE id = 69260;
UPDATE pages SET meta_description = 'Bluetooth datorā — Esmu dzirdējis, ka ir iespējams ielādēt Bluetooth datorā, un tad neizmantojot USB vadu pārsūtīt uz telefonu melodijas, motīvus...' WHERE id = 17144;
UPDATE pages SET meta_description = 'Naudas pelnīšana apkopojums — Meklējot kaut ko, nospied CTRL+F, un ieraksti, ko meklē. 150-200k stundā p2p iesācējiem Labs veids, kā pelnīt naudu Lielā...' WHERE id = 498;
UPDATE pages SET meta_description = 'EXS.lv #4 florbola turnīrs - PIETEIKŠANĀS — Labdien, sen nelasītie postotāji, mīļie un varbūt ne tik mīļie eksieši! Ir pagājis viens gads, četri mēneši...' WHERE id = 68036;
UPDATE pages SET meta_description = 'PHP/MySQL login sistēma ar sesijām — pilna lietotāju autorizācijas pamācība ar kodu.' WHERE id = 51817;
UPDATE pages SET meta_description = '5000 comments! ! ! — Tātad mazliet pašpikoju no tēmas, kur tika iegūs 1000 komentāru, bet šeit mēs varētu visi kopā uzraut virsmaz 5 tūkstošus...' WHERE id = 39521;
UPDATE pages SET meta_description = 'Savs cs 1.6 serveris — Tātad, ilgi nekavēšos un sākšu rakstīt. Lai izveidotu serveri un to uzturētu mums vajadzēs apmēram šādas minimālās prasības....' WHERE id = 41790;
UPDATE pages SET meta_description = 'Piedalies populārajā exs.lv foruma spēlē "Spēle: Neloģiskie jautājumi". Iesaisties diskusijās un uzspēlē kopā ar citiem biedriem!' WHERE id = 54186;
UPDATE pages SET meta_description = 'Smieklīgākie, nerātnākie nedarbi un notikumi dzīvē — Te nu nekautrējaties, un uzrakstat kādu no saviem foršākajiem vai stulbākajiem, nerātnākajiem vai...' WHERE id = 37298;
UPDATE pages SET meta_description = '"Sāc strādāt Bitē" negaidīti uzvar eXs.lv #4 florbola turnīrā — Komanda "Sāc strādāt Bitē" negaidīti uzvar eXs.lv florbola turnīrā "Atkušņa kauss \\'16"...' WHERE id = 68110;
UPDATE pages SET meta_description = 'Datora komplektēšana — Sveiki! Daudziem rodas jautājums, kur pirkt datoru un kādu labāk izvēlēties, lai atbildētu uz šo jautājumu mēģināsu rādīt dažus...' WHERE id = 50022;
UPDATE pages SET meta_description = 'Garšīgākais šoko batoniņš? — Čau! Nesen man uzdeva tādu jautājumu - kurš ir garšīgākais šokolādes batoniņš? Es nedaudz apmulsu. Tad nedaudz aizdomājos....' WHERE id = 44622;
UPDATE pages SET meta_description = 'Spied spied.!! — Pēdējā laikā esmu ievērojis, ka komentāriem aktīvāk tiek spiesti Plusiņi un Mīnusiņi. Vislabākais ir tas, ka tas ietekmē tavu KARMU...' WHERE id = 39827;
UPDATE pages SET meta_description = 'Izmaiņas lapas noteikumos — Labvakar exieši! Administrācija ir sagatavojusi patīkamas izmaiņas noteikumos miermīlīgajiem un inteliģentajiem lapas...' WHERE id = 68124;
UPDATE pages SET meta_description = 'Par ExsParty 2015! — Šoreiz, 2015.gadā, tiksimies jaukajā un mājīgajā pirtī Vētras, 28. un 29.augustā (piektdiena un sestdiena) mājīgā un klusā pirtiņā...' WHERE id = 67344;
UPDATE pages SET meta_description = 'The World of Kanako — Režisors: Tatsuya Nakashima Aktieri: Kôji Yakusho, Nana Komatsu, Satoshi Tsumabuki u.c. Sižets: Izbijušais detektīvs cenšas...' WHERE id = 68115;
UPDATE pages SET meta_description = 'Mekleju cs gungame serveri! — Vai kads nezin kadu gungame serveri?? :P ar norm pingiem??' WHERE id = 10465;
UPDATE pages SET meta_description = 'Katatonia — ir zviedru depresīvā roka/metāla grupa(sākotnēji: doom/death metāls), kas sākotnēji dibināta ar nosaukumu Melancholium 1987. gadā, bet...' WHERE id = 61526;
UPDATE pages SET meta_description = 'Emīlija, 1 vārda spēle! — Kaut kad nesen, latgals ierosināja spēlēt 1 vārda spēli moderatoru forumā. Beigu beigās sanāca super stāsts. Turpinam Tālāk,...' WHERE id = 40186;
UPDATE pages SET meta_description = 'Freedom Writers — Režisors : Richard LaGravenese Aktieri : Hilary Swank, Imelda Staunton, Patrick Dempsey Sižets: Jaunai skolotājai iedod klasi, kurā...' WHERE id = 68164;
UPDATE pages SET meta_description = 'Kāršu triki iesācējiem — Šeit es ielikšu pāris video iesācējiem, kas mācās kāršu trikus. video -' WHERE id = 40668;
UPDATE pages SET meta_description = 'Ziemasvētku Sveiciens! — Priecīgus Ziemasvētkus un laimīgu Jauno gadu jums novēl Rs.ex.lv administrācija un visi rakstu autori!! Nosviniet kārtīgi un...' WHERE id = 331;
UPDATE pages SET meta_description = 'Block Saraksts (Alpha) — Šeit būs aprakstīts tas, kādi kluči ir pieejami un kur viņus atrast/izveidot. Pa visu Minecraft pasauli ir...' WHERE id = 44060;
UPDATE pages SET meta_description = 'Smieklīgi joki un jautras anekdotes: Nerātnās anekdotes #1. Lasot rakstu, garantēts labs garastāvoklis!' WHERE id = 50360;
UPDATE pages SET meta_description = 'Ielu vingrošana — Kas ir ielu vingrošana? Ielu vingrošana ir a) atlētiskās vingrošanas, b) calisthenics, c)parkour un d) hip-hop kultūras un sporta...' WHERE id = 38891;
UPDATE pages SET meta_description = 'Grupa Monro - latviešu smagais metāls — "Monro" ir 1988. gadā dibināta leģendāra latviešu smagā metāla apvienība. Caur šo rakstu vēlos vairāk cilvēkiem...' WHERE id = 41157;
UPDATE pages SET meta_description = 'Ziemas kauss \\'14 — 22. februārī Bulduru Dārzkopības vidusskolā notiks nu jau trešais eXs.lv futzāla turnīrs "Ziemas Kauss \\'14". Turnīra sākums jau...' WHERE id = 63040;
UPDATE pages SET meta_description = 'The Wombats — ir angļu „indie rock” grupa, kura izveidojusies 2003. gadā, Anglijā, Liverpūlē. Grupu ir izveidojuši divi vietējie iedzīvotāji – Mattevs...' WHERE id = 61336;
UPDATE pages SET meta_description = 'PHP skripts ziņu un rakstu izvilkšanai no IPB 3.2/3.3 foruma datubāzes.' WHERE id = 51656;
UPDATE pages SET meta_description = 'Crafting 2.daļa — CRAFTING 2.daļa Ja nezinat, kā izveidot rīkus; akmeņu skaldīšanai; koku ciršanai; rakšanai; sēklu meklēšanai; spaiņus; kompasus u.c.,...' WHERE id = 44050;
UPDATE pages SET meta_description = 'EXS Geocaching — Īpaši nekavējoties garos ievadteikumos - šajā rakstā īsumā ir plānots pastāstīt, kas ir slēpņošana jeb geocaching un kāds tam vispār...' WHERE id = 68310;
UPDATE pages SET meta_description = 'Noderīga pamācība: Kā mēs nonācām līdz RS un Exam?. Viss sākās ļoti ļoti sen, kaut kādā 2002 gadā, kad man parādija runescape. Tā kā prasības bija...' WHERE id = 37260;
UPDATE pages SET meta_description = 'Vai viegli būt jaunam? — Oriģinālnosaukums: "Vai viegli būt jaunam?" Iznākšanas gads: 1987 Režisors: Juris Podnieks Scenārija autors: Ābrams Kleckins,...' WHERE id = 48545;
UPDATE pages SET meta_description = 'Vecās pagastmājas mistērija — Žanrs: Mana iecienītākā filma, Trilleris, Drāma Režisors: Jānis Streičs Galvenajās lomās: Andris Bērziņš, Renārs Kaupers,...' WHERE id = 4632;
UPDATE pages SET meta_description = 'Noderīga pamācība: Kā uztaisīt caurspīdīgu špikeri. Kā jau mēs visi zinām, katram no mums ir nācies špikot. Bieži vien jūs tiekat pieķerts, bet vienmēr...' WHERE id = 46696;
UPDATE pages SET meta_description = 'Kur var salikt datoru? — Lūdzu pasakat adresi kurā pats var salikt datoru pa dalam un parada cik tas maksā.ka arī pa cik varētu pardod šādu datoru:...' WHERE id = 37942;
UPDATE pages SET meta_description = 'Free membership Update — Čau, nu atkal jauna diena, bet šodien diemžēl loterijas nebūs... Nē, nē neuztraucieties viņas notiksies, bet 1x nedēļā, kd...' WHERE id = 37595;
UPDATE pages SET meta_description = 'PDFresizer.com — bezmaksas online rīks PDF failu apstrādei, apgriešanai un optimizācijai.' WHERE id = 66258;
