// Generated by CoffeeScript 1.7.1 & EXS.LV Integration
(function() {
  function setup() {
    var $, a, defaultControls, getWebGL, hasWebGL, init, s, u, _fn, _i, _len;

    $ = function(_) {
      return document.getElementById(_);
    };

    init = function(controlType, quality, hud, godmode) {
      var hexGL, progressbar;
      var gameBox = $('hexgl-game-box');
      var w = gameBox ? gameBox.clientWidth : window.innerWidth;
      var h = gameBox ? gameBox.clientHeight : 550;

      hexGL = new bkcore.hexgl.HexGL({
        document: document,
        width: w,
        height: h,
        container: $('main'),
        overlay: $('overlay'),
        gameover: $('step-5'),
        quality: quality,
        difficulty: 0,
        hud: hud === 1,
        controlType: controlType,
        godmode: godmode,
        track: 'Cityscape'
      });
      window.hexGL = hexGL;
      progressbar = $('progressbar');
      return hexGL.load({
        onLoad: function() {
          console.log('LOADED.');
          hexGL.init();
          $('step-3').style.display = 'none';
          $('step-4').style.display = 'block';
          return hexGL.start();
        },
        onError: function(s) {
          return console.error("Error loading " + s + ".");
        },
        onProgress: function(p, t, n) {
          console.log("LOADED " + t + " : " + n + " ( " + p.loaded + " / " + p.total + " ).");
          if (progressbar) {
            progressbar.style.width = "" + (p.loaded / p.total * 100) + "%";
          }
        }
      });
    };

    u = bkcore.Utils ? bkcore.Utils.getURLParameter : function() { return null; };

    defaultControls = (bkcore.Utils && bkcore.Utils.isTouchDevice && bkcore.Utils.isTouchDevice()) ? 1 : 0;

    s = [
      ['controlType', ['KEYBOARD', 'TOUCH', 'LEAP MOTION CONTROLLER', 'GAMEPAD'], defaultControls, defaultControls, 'Vadība: '],
      ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 3, 3, 'Kvalitāte: '],
      ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '],
      ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']
    ];

    _fn = function(a) {
      var e, f, _ref;
      a[3] = (_ref = u(a[0])) != null ? _ref : a[2];
      e = $("s-" + a[0]);
      if (!e) return;
      (f = function() {
        return e.innerHTML = a[4] + a[1][a[3]];
      })();
      return e.onclick = function() {
        return f(a[3] = (a[3] + 1) % a[1].length);
      };
    };
    for (_i = 0, _len = s.length; _i < _len; _i++) {
      a = s[_i];
      _fn(a);
    }

    var step2 = $('step-2');
    if (step2) {
      step2.onclick = function() {
        step2.style.display = 'none';
        $('step-3').style.display = 'block';
        return init(s[0][3], s[1][3], s[2][3], s[3][3]);
      };
    }

    var step5 = $('step-5');
    if (step5) {
      step5.onclick = function() {
        return window.location.reload();
      };
    }

    var sCredits = $('s-credits');
    if (sCredits) {
      sCredits.onclick = function() {
        $('step-1').style.display = 'none';
        return $('credits').style.display = 'block';
      };
    }

    var credits = $('credits');
    if (credits) {
      credits.onclick = function() {
        $('step-1').style.display = 'block';
        return $('credits').style.display = 'none';
      };
    }

    hasWebGL = function() {
      var canvas, gl;
      gl = null;
      canvas = document.createElement('canvas');
      try {
        gl = canvas.getContext("webgl");
      } catch (_error) {}
      if (gl == null) {
        try {
          gl = canvas.getContext("experimental-webgl");
        } catch (_error) {}
      }
      return gl != null;
    };

    var startBtn = $('start');
    if (startBtn) {
      if (!hasWebGL()) {
        startBtn.innerHTML = 'WebGL navigation is not supported!';
        startBtn.onclick = function() {
          return window.location.href = 'http://get.webgl.org/';
        };
      } else {
        startBtn.onclick = function() {
          // Fetch session token for EXS.lv score submit
          fetch('/hexgl?action=init_token')
            .then(function(res) { return res.json(); })
            .then(function(data) {
              if (data && data.token) {
                window.hexGLSessionToken = data.token;
              }
            })
            .catch(function(e) {});

          $('step-1').style.display = 'none';
          $('step-2').style.display = 'block';
          var basePath = window.hexGLBasePath || '/modules/hexgl/';
          if (basePath.charAt(basePath.length - 1) !== '/') basePath += '/';
          return $('step-2').style.backgroundImage = "url(" + basePath + "css/help-" + s[0][3] + ".png)";
        };
      }
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', setup);
  } else {
    setup();
  }
}).call(this);
